/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2018-01-11 14:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.student.content;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("file:/C:/Users/dell/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar", Long.valueOf(1512350669591L));
    _jspx_dependants.put("jar:file:/C:/Users/dell/.m2/repository/org/springframework/spring-webmvc/5.0.0.RELEASE/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1506567796000L));
    _jspx_dependants.put("file:/C:/Users/dell/.m2/repository/org/springframework/spring-webmvc/5.0.0.RELEASE/spring-webmvc-5.0.0.RELEASE.jar", Long.valueOf(1512350606004L));
    _jspx_dependants.put("/commons/taglibs.jsp", Long.valueOf(1510901652000L));
    _jspx_dependants.put("jar:file:/C:/Users/dell/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/Users/dell/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"studentAddPanel\">\n");
      out.write("\t<div class=\"headline\">\n");
      out.write("\t\t<h2>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t新增学生\n");
      out.write("\n");
      out.write("\t\t</h2>\n");
      out.write("\t</div>\n");
      out.write("\t<form class=\"real-content-form form\" name=\"student\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/student/content/save\" method=\"post\">\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">名称</label> <input name=\"name\" class=\"input-content\" type=\"text\" placeholder=\"请输入姓名\" >\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">性别</label> \n");
      out.write("\t\t\t<div class=\"radio-content\">\n");
      out.write("\t\t\t\t<label><input type=\"radio\" name=\"gener\" value=\"男\" checked> 男</label>\n");
      out.write("\t\t\t\t<label><input type=\"radio\" name=\"gener\" value=\"女 \">女</label>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">专业</label> <input name=\"object\" class=\"input-content\" type=\"text\" placeholder=\"请输入专业\" >\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">方向</label> <input name=\"direction\" class=\"input-content\" type=\"text\" placeholder=\"请输入姓名\" >\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">技术</label> <input name=\"technology\" class=\"input-content\" type=\"text\" placeholder=\"请输入技术\" onkeyup=\"this.value=this.value.replace(/[^\\d]/g,'')\" >\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<label class=\"input-label\">能力</label> <input name=\"ability\" class=\"input-content\" type=\"text\" placeholder=\"请输入能力\" onkeyup=\"this.value=this.value.replace(/[^\\d]/g,'')\" >\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\t<div class=\"bottom-menu-panel\">\n");
      out.write("\t\t<button class=\"btn btn-bg save-student-btn\">保存</button>\n");
      out.write("\t\t<button class=\"btn btn-bg cancel-btn\">取消</button>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t$(function() {\n");
      out.write("\t\tvar $studentAddPanel = $(\"#studentAddPanel\");\n");
      out.write("\t\tvar $studentContentForm = $studentAddPanel.find(\"form\");\n");
      out.write("\n");
      out.write("\t\t// 初始化表单提交\n");
      out.write("\t\t$studentContentForm.on(\"submit\", function(e) {\n");
      out.write("\t\t\t// 阻止表单默认提交事件\n");
      out.write("\t\t\te.preventDefault();\n");
      out.write("\n");
      out.write("\t\t\tvar $this = $(this);\n");
      out.write("\n");
      out.write("\t\t\t// jquery-form的异步提交方式\n");
      out.write("\t\t\t$this.ajaxSubmit({\n");
      out.write("\t\t\t\tbeforeSubmit : function(data, $form) {\n");
      out.write("\t\t\t\t\tvar name = $form.find(\"input[name='name']\");\n");
      out.write("\t\t\t\t\tvar object = $form.find(\"input[name='object']\");\n");
      out.write("\t\t\t\t\tvar direction = $form.find(\"input[name='direction']\");\n");
      out.write("\t\t\t\t\tvar technology = $form.find(\"input[name='technology']\");\n");
      out.write("\t\t\t\t\tvar ability = $form.find(\"input[name='ability']\");\n");
      out.write("\n");
      out.write("\t\t\t\t\tif ($.trim(name.val()) === \"\") {\n");
      out.write("\t\t\t\t\t\treturn showInputTip(name, \"请输入姓名\");\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\thideInputTip(name);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\tif ($.trim(object.val()) === \"\") {\n");
      out.write("\t\t\t\t\t\treturn showInputTip(object, \"请输入专业\");\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\thideInputTip(object);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif ($.trim(direction.val()) === \"\") {\n");
      out.write("\t\t\t\t\t\treturn showInputTip(direction, \"请输入方向\");\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\thideInputTip(direction);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif ($.trim(technology.val()) === \"\") {\n");
      out.write("\t\t\t\t\t\treturn showInputTip(technology, \"请输入技术\");\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\thideInputTip(technology);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif ($.trim(ability.val()) === \"\") {\n");
      out.write("\t\t\t\t\t\treturn showInputTip(ability, \"请输入能力\");\n");
      out.write("\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\thideInputTip(ability);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess : function() {\n");
      out.write("\t\t\t\t\t// 刷新页面\n");
      out.write("\t\t\t\t\ttriggerCurrentMenu();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t// 保存学生\n");
      out.write("\t\t$studentAddPanel.find(\".save-student-btn\").on(\"click\", function() {\n");
      out.write("\t\t\t$studentContentForm.trigger(\"submit\");\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t// 取消保存\n");
      out.write("\t\t$studentAddPanel.find(\".cancel-btn\").on(\"click\", function() {\n");
      out.write("\t\t\t// 刷新页面\n");
      out.write("\t\t\ttriggerCurrentMenu();\n");
      out.write("\t\t});\n");
      out.write("\t})\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/taglibs.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/taglibs.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    }
    return false;
  }
}
